### ISSUE TITLE
Problem with running visualizer; 'bash: ahrs-visualizer: command not found'

### ISSUE THREAD

**Issue by PieterHerings** [DavidEGrayson/ahrs-visualizer#10]
Hi again,

The ahrs system is working correctly and I calibrated the minIMU-9 v5 sensor, but I am now facing a problem with running the visualizer. I installed the libpng-dev libraries and run 'sudo make install' in the source code. 

What should I put in front of 'minimu9-ahrs | ahrs-visualizer' to make it run? And where should I type this? 

Thanks again, my project is really getting somewhere because of your help.

**Comment by DavidEGrayson** [comment]
You need to make sure that the directory holding `ahrs-visualizer` is on your PATH or you need to specify the path to it when you run it.  Please find some tutorials about how to use Bash and Linux.
