### ISSUE TITLE
Raspberry Pi dependencies

### ISSUE THREAD

**Issue by Squonk42** [DavidEGrayson/ahrs-visualizer#5]
Can you explicit what is RPi-specific in GPU code, please?

**Comment by DavidEGrayson** [comment]
The function calls like `bcm_host_init();` and `bcm_host_deinit();` refer to the particular SoC used on the Raspberry Pi in their name so I think that is the main thing.

I think the code is still pretty portable but you might need some #ifdefs to call a more appropriate function for your board, or change it to call something more generic.  Or maybe those BCM functions aren't even needed anymore; I don't know.

**Comment by Squonk42** [comment]
OK, thank you for your answer, I will dig further based on these hints!
