### ISSUE TITLE
failed to get display size

### ISSUE THREAD

**Issue by Tms-bodnar** [DavidEGrayson/ahrs-visualizer#9]
First of all, thank you, your work is awesome.
when i started the app, i got the failed to get display size error.
`minimu9-ahrs -b /dev/i2c-1 | ahrs-visualizer
Error: Failed to get display size.
`
i use on raspi zero w, raspbian buster, and the same happend, when i started  in ssh cmd, or vnc desktop.
i checked the
`graphics_get_display_size(0 /* LCD */, &screen_width, &screen_height);`
funcion's documentation, but i didn't find the solution.
please, share with me any ideas.
thank you

**Comment by DavidEGrayson** [comment]
If you haven't done so already, I would try running ahrs-visualizer in a text terminal of the Raspberry Pi.  Don't use X, don't use SSH.

**Comment by Tms-bodnar** [comment]
Ok, thanks for the quick reply i'll try it.
